--DEFINE STAGING TABLES FOR NATIVE SYNTHEA DATA

CREATE TABLE [synthea].ALLERGIES
(
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].CAREPLANS
(
    Id VARCHAR(1000) NULL,
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    REASONCODE VARCHAR(255) NULL,
    REASONDESCRIPTION VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].CONDITIONS
(
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].DEVICES
(
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    UDI VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].ENCOUNTERS
(
    Id VARCHAR(1000) NULL,
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ORGANIZATION VARCHAR(1000) NULL,
    PROVIDER VARCHAR(1000) NULL,
    PAYER VARCHAR(1000) NULL,
    ENCOUNTERCLASS VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    BASE_ENCOUNTER_COST NUMERIC(18, 0) NULL,
    TOTAL_CLAIM_COST NUMERIC(18, 0) NULL,
    PAYER_COVERAGE NUMERIC(18, 0) NULL,
    REASONCODE VARCHAR(100) NULL,
    REASONDESCRIPTION VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].IMAGING_STUDIES
(
    Id VARCHAR(1000) NULL,
    DATE DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    SERIES_UId VARCHAR(1000) NULL,
    BODYSITE_CODE VARCHAR(100) NULL,
    BODYSITE_DESCRIPTION VARCHAR(255) NULL,
    MODALITY_CODE VARCHAR(100) NULL,
    MODALITY_DESCRIPTION VARCHAR(255) NULL,
    INSTANCE_UId VARCHAR(1000) NULL,
    SOP_CODE VARCHAR(100) NULL,
    SOP_DESCRIPTION VARCHAR(255) NULL,
    PROCEDURE_CODE VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);


CREATE TABLE [synthea].IMMUNIZATIONS
(
    DATE DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    BASE_COST NUMERIC(18, 0) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].MEDICATIONS
(
    START DATE NULL,
    STOP DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    PAYER VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    BASE_COST NUMERIC(18, 0) NULL,
    PAYER_COVERAGE NUMERIC(18, 0) NULL,
    DISPENSES INT NULL,
    TOTALCOST NUMERIC(18, 0) NULL,
    REASONCODE VARCHAR(100) NULL,
    REASONDESCRIPTION VARCHAR(255) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].OBSERVATIONS
(
    DATE DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    VALUE VARCHAR(1000) NULL,
    UNITS VARCHAR(100) NULL,
    TYPE VARCHAR(100) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].ORGANIZATIONS
(
    Id VARCHAR(1000) NULL,
    NAME VARCHAR(1000) NULL,
    ADDRESS VARCHAR(1000) NULL,
    CITY VARCHAR(100) NULL,
    STATE VARCHAR(100) NULL,
    ZIP VARCHAR(100) NULL,
    LAT NUMERIC(18, 0) NULL,
    LON NUMERIC(18, 0) NULL,
    PHONE VARCHAR(100) NULL,
    REVENUE FLOAT NULL,
    UTILIZATION VARCHAR(100) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].PATIENTS
(
    Id VARCHAR(1000) NULL,
    BIRTHDATE DATE NULL,
    DEATHDATE DATE NULL,
    SSN VARCHAR(100) NULL,
    DRIVERS VARCHAR(100) NULL,
    PASSPORT VARCHAR(100) NULL,
    PREFIX VARCHAR(100) NULL,
    FIRST VARCHAR(100) NULL,
    LAST VARCHAR(100) NULL,
    SUFFIX VARCHAR(100) NULL,
    MAIDEN VARCHAR(100) NULL,
    MARITAL VARCHAR(100) NULL,
    RACE VARCHAR(100) NULL,
    ETHNICITY VARCHAR(100) NULL,
    GENDER VARCHAR(100) NULL,
    BIRTHPLACE VARCHAR(100) NULL,
    ADDRESS VARCHAR(100) NULL,
    CITY VARCHAR(100) NULL,
    STATE VARCHAR(100) NULL,
    COUNTY VARCHAR(100) NULL,
    ZIP VARCHAR(100) NULL,
    LAT NUMERIC(18, 0) NULL,
    LON NUMERIC(18, 0) NULL,
    HEALTHCARE_EXPENSES NUMERIC(18, 0) NULL,
    HEALTHCARE_COVERAGE NUMERIC(18, 0) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].PROCEDURES
(
    DATE DATE NULL,
    PATIENT VARCHAR(1000) NULL,
    ENCOUNTER VARCHAR(1000) NULL,
    CODE VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(255) NULL,
    BASE_COST NUMERIC(18, 0) NULL,
    REASONCODE VARCHAR(1000) NULL,
    REASONDESCRIPTION VARCHAR(1000) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);

CREATE TABLE [synthea].PROVIDERS
(
    Id VARCHAR(1000) NULL,
    ORGANIZATION VARCHAR(1000) NULL,
    NAME VARCHAR(100) NULL,
    GENDER VARCHAR(100) NULL,
    SPECIALITY VARCHAR(100) NULL,
    ADDRESS VARCHAR(255) NULL,
    CITY VARCHAR(100) NULL,
    STATE VARCHAR(100) NULL,
    ZIP VARCHAR(100) NULL,
    LAT NUMERIC(18, 0) NULL,
    LON NUMERIC(18, 0) NULL,
    UTILIZATION NUMERIC(18, 0) NULL
)
WITH (DISTRIBUTION=ROUND_ROBIN);







